export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  ADD_NEW_PATIENT: "ADD_NEW_PATIENT",
  FETCH_PATIENTS: "FETCH_PATIENTS",
  FETCH_PATIENT: "FETCH_PATIENT",
  FETCH_CHANGWATS: "FETCH_CHANGWATS",
  FETCH_AMPHURS: "FETCH_AMPHURS",
  GET_AMPHUR: "GET_AMPHUR",
  FETCH_TAMBONS: "FETCH_TAMBONS",
  GET_TAMBON: "GET_TAMBON",
};
